export * from './GameOverHeading';
export * from './HighscoreHeading';
export * from './InputHint';
export * from './LevelTitle';
export * from './MainHeading';
export * from './SceneMenuTitle';
export * from './SpriteText';
export * from './TerrainText';
export * from './VictoryHeading';
