export enum GameSceneType {
  EditorEnemy,
  EditorMap,
  EditorMenu,
  LevelLoad,
  LevelPlay,
  LevelScore,
  LevelSelection,
  MainGameOver,
  MainHighscore,
  MainMenu,
  MainVictory,
  SettingsKeybinding,
  SettingsMenu,
  SandboxTransform,
}
